from dotenv import dotenv_values

config = dotenv_values("../.env")
TOKEN_API = config["NTO_TELEGRAM_BOT_TOKEN"]
BOT_WEBHOOK_HOST = config["NTO_TELEGRAM_BOT_WEBHOOK_HOST"]
BOT_WEBHOOK_PORT = config["NTO_TELEGRAM_BOT_WEBHOOK_PORT"]

BOT_WEBHOOK_URL = f"{BOT_WEBHOOK_HOST}:{BOT_WEBHOOK_PORT}"

MQTT_HOST = config["NTO_TELEGRAM_MQTT_HOST"]
MQTT_PORT = config["NTO_TELEGRAM_MQTT_PORT"]
MQTT_USERNAME = config["NTO_TELEGRAM_MQTT_USERNAME"]
MQTT_PASSWORD = config["NTO_TELEGRAM_MQTT_PASSWORD"]
MQTT_CLIENT_ID = config["NTO_TELEGRAM_MQTT_CLIENT_ID"]
