import os
from dotenv import load_dotenv

load_dotenv()

TOKEN_API = os.environ.get("NTO_TELEGRAM_BOT_TOKEN")
BOT_WEBHOOK_HOST = os.environ.get("NTO_TELEGRAM_BOT_WEBHOOK_HOST")
BOT_WEBHOOK_PORT = os.environ.get("NTO_TELEGRAM_BOT_WEBHOOK_PORT")

BOT_WEBHOOK_URL = f"{BOT_WEBHOOK_HOST}:{BOT_WEBHOOK_PORT}"

MQTT_HOST = os.environ.get("NTO_TELEGRAM_MQTT_HOST")
MQTT_PORT = os.environ.get("NTO_TELEGRAM_MQTT_PORT")
MQTT_USERNAME = os.environ.get("NTO_TELEGRAM_MQTT_USERNAME")
MQTT_PASSWORD = os.environ.get("NTO_TELEGRAM_MQTT_PASSWORD")
MQTT_CLIENT_ID = os.environ.get("NTO_TELEGRAM_MQTT_CLIENT_ID")

POSTGRES_HOST = os.environ.get("NTO_POSTGRES_HOST")
POSTGRES_PORT = os.environ.get("NTO_POSTGRES_PORT")
POSTGRES_DB = os.environ.get("NTO_POSTGRES_DB")
POSTGRES_USER = os.environ.get("NTO_POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("NTO_POSTGRES_PASSWORD")

# driver://user:pass@localhost/dbname
POSTGRES_URI = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
