"""change telegram_id type

Revision ID: 6463fe8ed261
Revises: e59cc386ffdf
Create Date: 2023-03-05 14:55:09.652115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6463fe8ed261'
down_revision = 'e59cc386ffdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=False, unique=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.add_column('users', sa.Column('telegram_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###
