"""Database creation

Revision ID: e59cc386ffdf
Revises: 
Create Date: 2023-02-26 16:03:57.745749

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e59cc386ffdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=True),
                    sa.Column('telegram_id', sa.BigInteger(), nullable=False, unique=True),
                    sa.Column('is_admin', sa.Boolean(), nullable=True),
                    sa.Column('start_usage', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('telegram_id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('topics',
                    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('topic', sa.String(length=50), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('topic_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    op.drop_table('users')
    # ### end Alembic commands ###
