version: "3.9"

services:
  postgres:
    container_name: nto-postgres
    image: postgres:${NTO_POSTGRES_TAG}
    environment:
      POSTGRES_DB: "${NTO_POSTGRES_DB}"
      POSTGRES_USER: "${NTO_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${NTO_POSTGRES_PASSWORD}"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgres/data
    ports:
      - ${NTO_POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NTO_POSTGRES_USER} -d ${NTO_POSTGRES_DB}" ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - base_network

  pgadmin:
    container_name: nto-pgadmin
    image: dpage/pgadmin4:${NTO_PGADMIN_TAG}
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: "${NTO_PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${NTO_PGADMIN_DEFAULT_PASSWORD}"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - ${NTO_PGADMIN_PORT}:80
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - base_network

networks:
  base_network:
    name: postgres
